language: python
python:
  - "3.5"

services:
  - postgresql

addons:
  postgresql: "10.10"

install:
  - pip install codecov tox

script:
  - tox --

after_success:
  - codecov

env:
  - TOXENV=py36-django21
  - TOXENV=py37-django21
  - TOXENV=py38-django21

  - TOXENV=py36-django22
  - TOXENV=py37-django22
  - TOXENV=py38-django22
