language: python
python:
  - "3.5"

services:
  - postgresql

addons:
  postgresql: "10.10"

install:
  - pip install codecov tox

script:
  - tox --

after_success:
  - codecov

env:
  - TOXENV=py35-django2.1
  - TOXENV=py36-django2.1
  - TOXENV=py37-django2.1
  - TOXENV=py38-django2.1

  - TOXENV=py35-django2.2
  - TOXENV=py36-django2.2
  - TOXENV=py37-django2.2
  - TOXENV=py38-django2.2
