language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - postgresql

addons:
  postgresql: "10.10"

install:
  - pip install codecov tox

before_script:
  - psql -c 'CREATE DATABASE tracking_analyzer_test;' -U postgres

script:
  - tox --

after_success:
  - codecov

env:
  - TOXENV=django21
  - TOXENV=django22
